/* Entry -> actual classroom assets, using synthetic users and loopback only.
 * Real entry decisions/HTML are generated by make_browser_fixtures.py.
 */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os');
const {spawn}=require('node:child_process');const WebSocket=require('ws');
const ROOT=path.resolve(__dirname,'../..'),PUBLIC=path.join(ROOT,'tongjianyun/public');
const fixture=JSON.parse(fs.readFileSync(process.env.TEACHER_ENTRY_FIXTURES||'/tmp/tjy-teacher-entry-fixtures.json','utf8'));
const OUT=process.env.TEACHER_ENTRY_OUTPUT||'/tmp/tjy-teacher-entry-review';fs.mkdirSync(OUT,{recursive:true});
const CHROME=process.env.CLASSROOM_TEST_CHROME||'/home/zyd/.cache/ms-playwright/chromium_headless_shell-1228/chrome-linux/headless_shell';
let actor='single',records=[],calls=[],errors=[],redirects=[];
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function overview(args){
  const m=fixture.cases[actor].model,g=m.groups.find(g=>g.name===args.student_group)||m.groups[0];
  if(!g)throw Error('No teacher groups');
  const students=[1,2].map(i=>({student:'DEMO-S'+i,student_name:'验收幼儿'+i,roll_number:i,status:records.includes(i)?'Present':'Unknown',source:'隔离验收',modified:''}));
  return {workspace:'teacher',groups:m.groups,group:{name:g.name,label:g.student_group_name},day:args.day||'2026-09-23',today:'2026-09-23',generated_at:'2026-09-23 10:00:00',user_label:m.user_label,scene:{mode:'illustrative',location_connected:false},
    attendance:{available:true,students,revision:'test-rev',counts:{Present:records.length,Absent:0,Leave:0,Unknown:2-records.length,total:2,rate:records.length/2*100}},
    capabilities:{attendance_write:true,meals_write:true,log_create:false,health:false,future:false},health:{available:false},
    meals:{available:true,has_plan:false,actual:null,expected:{lunch_count:2}},schedule:{available:false,rows:[]},logs:{available:false,rows:[]}};
}
const server=http.createServer(async(req,res)=>{
  try{
    const url=new URL(req.url,'http://localhost');
    if(url.pathname==='/apps'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(`<html lang="zh-CN"><title>入口链路验收（合成）</title><a data-app="tongjianyun" href="${fixture.icon_route}">童健云</a></html>`);return;}
    if(url.pathname==='/tongjianyun-entry'){
      const key=new URLSearchParams([...url.searchParams].sort(([a],[b])=>a.localeCompare(b))).toString();
      const result=fixture.cases[actor].routes[key];if(!result){res.writeHead(400);res.end('Unexpected fixture route');return;}
      res.writeHead(result.status,{'Content-Type':'text/html; charset=utf-8',...result.headers,...(result.location?{Location:result.location}:{})});
      if(result.location)redirects.push(result.location);res.end(result.body||'');return;
    }
    if(url.pathname==='/tongjianyun-classroom'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync(path.join(ROOT,'tongjianyun/www/tongjianyun-classroom.html'),'utf8').replace('{{ csrf_token | e }}','isolated-test-csrf'));return;}
    if(url.pathname==='/desk/tongjianyun-workbench'||url.pathname==='/login'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end('<h1>原有入口（验收占位）</h1>');return;}
    if(url.pathname.startsWith('/api/method/')){
      let raw='';for await(const chunk of req)raw+=chunk;
      const args=req.method==='POST'?JSON.parse(raw):Object.fromEntries(url.searchParams),method=url.pathname.split('/').pop();
      calls.push({method,args,write:req.method==='POST'});let result;
      if(args.workspace!=='teacher'||!fixture.cases[actor].model.groups.some(g=>g.name===args.student_group)){
        res.writeHead(403,{'Content-Type':'application/json'});res.end('{}');return;
      }
      if(method==='tongjianyun.classroom.get_overview')result=overview(args);
      else if(method==='tongjianyun.classroom.get_meals')result={record:{status:'待确认',students:[1,2].map(i=>({student:'DEMO-S'+i,student_name:'验收幼儿'+i,lunch_expected:1,dinner:'不供餐'}))},revision:'meal-test',expected:{lunch_count:2},actual:{}};
      else if(method==='tongjianyun.classroom.save_attendance'){assert.equal(args.revision,'test-rev');records=args.changes.filter(c=>c.status==='Present').map(c=>Number(c.student.slice(-1)));result={saved:records.length};}
      else throw Error('Unexpected API '+method);
      res.setHeader('Content-Type','application/json');res.end(JSON.stringify({message:result}));return;
    }
    const file=url.pathname.startsWith('/assets/tongjianyun/')?path.resolve(PUBLIC,decodeURIComponent(url.pathname.slice(20))):null;
    if(!file||!file.startsWith(PUBLIC+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}
    res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));
  }catch(e){errors.push(e.message);res.writeHead(500);res.end('{}');}
});
class CDP{
  constructor(url){this.next=0;this.pending=new Map();this.ws=new WebSocket(url);this.ready=new Promise(r=>this.ws.once('open',r));this.ws.on('message',raw=>{const m=JSON.parse(raw);if(m.id){const p=this.pending.get(m.id);if(p){this.pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);});}
  async send(method,params={},sessionId){await this.ready;return new Promise((resolve,reject)=>{const id=++this.next,timer=setTimeout(()=>{this.pending.delete(id);reject(Error('CDP timeout: '+method));},30000);this.pending.set(id,{resolve,reject,timer});this.ws.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})}));});}
}
(async()=>{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
  const profile=fs.mkdtempSync(path.join(os.tmpdir(),'tjy-teacher-entry-browser-'));
  let browser,cdp;
  try{
    browser=spawn(CHROME,['--no-sandbox','--disable-dev-shm-usage','--use-angle=swiftshader','--enable-unsafe-swiftshader','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
    let output='';const socket=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Browser start timeout')),15000);browser.stderr.on('data',b=>{output+=String(b);const match=output.match(/DevTools listening on (ws:\/\/\S+)/);if(match){clearTimeout(timer);resolve(match[1]);}});browser.once('error',reject);});
    cdp=new CDP(socket);const target=await cdp.send('Target.createTarget',{url:'about:blank'}),session=(await cdp.send('Target.attachToTarget',{targetId:target.targetId,flatten:true})).sessionId;
    const send=(m,p={})=>cdp.send(m,p,session);await send('Page.enable');await send('Runtime.enable');
    const run=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value;};
    const until=async expression=>{for(let i=0;i<100;i++){if(await run(expression))return;await delay(150);}throw Error('Timed out: '+expression);};
    const click=selector=>run(`document.querySelector(${JSON.stringify(selector)}).click()`);
    const go=async route=>{await send('Page.navigate',{url:origin+route});await delay(250);};
    const shot=async name=>{const s=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(OUT,name),Buffer.from(s.data,'base64'));};
    const ready=`document.querySelector('#scene-loading')?.hidden && document.querySelector('#class-select')?.value==='DEMO-C1'`;
    await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
    await send('Emulation.setDeviceMetricsOverride',{width:1440,height:960,deviceScaleFactor:1,mobile:false});
    await go('/apps');await click('[data-app="tongjianyun"]');await until(ready);
    assert.equal(await run(`new URLSearchParams(location.search).get('workspace')`),'teacher');
    assert.equal(await run(`document.body.classList.contains('teacher-workspace')`),true);
    assert.equal(await run(`document.querySelectorAll('#class-select option').length`),1);
    await shot('teacher-classroom.png');
    await click('#scene-labels [data-action="attendance"]');await until(`!!document.querySelector('#mark-pending')`);
    await run('window.confirm=()=>true');await click('#mark-pending');await click('#save-attendance');await until(`!document.querySelector('#business-dialog').open && document.querySelector('#page-message').hidden`);
    assert.equal(records.length,2);assert(calls.filter(r=>r.write).every(r=>r.args.workspace==='teacher'&&r.args.student_group==='DEMO-C1'));
    await click('#scene-labels [data-action="meals"]');await until(`!!document.querySelector('#confirm-meals')`);await click('#dialog-close');
    assert(!calls.some(c=>c.method.startsWith('tongjianyun.student_meals.')));
    await click('.header-return');await until(`document.querySelectorAll('[data-group-choice]').length===1`);

    actor='multi';await go('/tongjianyun-entry');await until(`document.querySelectorAll('[data-group-choice]').length===2`);await shot('teacher-choose-class.png');
    await click('[data-group-choice]:last-child');await until(`document.querySelector('#class-select')?.value==='DEMO-C2' && document.querySelector('#scene-loading')?.hidden`);
    assert.equal(await run(`document.querySelectorAll('#class-select option').length`),2);

    actor='dual';await go('/tongjianyun-entry');await until(`document.querySelectorAll('[data-profile]').length===2`);await shot('teacher-choose-work.png');
    await click('[data-profile="business"]');await until(`location.pathname==='/desk/tongjianyun-workbench'`);
    await go('/tongjianyun-entry');await click('[data-profile="teacher"]');await until(ready);

    actor='setup';const before=calls.length;await go('/tongjianyun-entry');await until(`!!document.querySelector('.checklist')`);await shot('teacher-needs-setup.png');assert.equal(calls.length,before);
    assert.equal(await run(`document.querySelectorAll('[data-group-choice]').length`),0);
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await delay(150);assert(await run(`document.documentElement.scrollWidth<=innerWidth+1`));await shot('teacher-setup-mobile.png');
    actor='multi';await go('/tongjianyun-entry');await until(`document.querySelectorAll('[data-group-choice]').length===2`);assert(await run(`document.documentElement.scrollWidth<=innerWidth+1`));await shot('teacher-class-mobile.png');
    const forbidden=await fetch(origin+'/tongjianyun-entry?profile=teacher&class=FOREIGN');assert.equal(forbidden.status,403);
    actor='operator';await go('/tongjianyun-entry');await until(`location.pathname==='/desk/tongjianyun-workbench'`);
    actor='unknown';await go('/tongjianyun-entry');await until(`!!document.querySelector('.setup')`);
    actor='guest';await go('/tongjianyun-entry');await until(`location.pathname==='/login'`);assert.equal(await run(`new URLSearchParams(location.search).get('redirect-to')`),'/tongjianyun-entry');
    assert.equal(errors.length,0,errors.join('\n'));
    console.log(JSON.stringify({passed:true,checks:['native-declared icon route','single teacher direct classroom','teacher marker survives history','only assigned class options','teacher-scoped attendance save','teacher-scoped meal read','workspace return','multiple classes chooser','multiple work identities chooser','business route preserved','unassigned has no student API read','mobile selection without overflow','foreign class rejected','unrecognized identity setup','guest login return'],synthetic_posts:calls.filter(r=>r.write).length,script_errors:errors.length,screenshots:OUT}));
  }finally{
    if(cdp){await cdp.send('Browser.close').catch(()=>{});cdp.ws.close();}
    if(browser&&browser.exitCode===null&&browser.signalCode===null){await Promise.race([new Promise(r=>browser.once('exit',r)),delay(3000)]);if(browser.exitCode===null&&browser.signalCode===null)browser.kill();}
    server.close();await delay(300);fs.rmSync(profile,{recursive:true,force:true,maxRetries:8,retryDelay:250});
  }
})().catch(e=>{console.error(e.stack);server.close();process.exit(1);});
