import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const text=await readFile(new URL('../public/meal_scene/state.js',import.meta.url),'utf8');
const {STEPS,stepFor,stepBadge,factCards,professionalRoute,mealDraft,draftTotals,number,esc}=await import('data:text/javascript;base64,'+Buffer.from(text).toString('base64'));
const cases=[];const test=(name,run)=>{run();cases.push(name);};
const model={capabilities:{recipe:true,order:true,receipt:true,stock:true,meals:true},recipes:{rows:[],has_more:false},orders:{rows:[],has_more:false},receipts:{rows:[],has_more:false},plans:{summary:{planned_groups:1,visible_groups:2,confirmed_groups:0,expected:null,actual:null}}};
test('eight ordered distinct stations',()=>{assert.equal(STEPS.length,8);assert.deepEqual(STEPS.map(s=>s.number),[1,2,3,4,5,6,7,8]);assert.equal(new Set(STEPS.map(s=>s.id)).size,8);});
test('serpentine coordinates make business order readable',()=>{assert(STEPS[0].point[0]<STEPS[1].point[0]);assert(STEPS[4].point[0]>STEPS[5].point[0]);assert(STEPS[4].point[2]>STEPS[3].point[2]);});
test('all anchors finite',()=>STEPS.forEach(s=>assert(s.point.every(Number.isFinite))));
test('unknown is not zero',()=>{assert.equal(number(null),'待核对');assert.equal(number(0),'0');});
test('partial plans never become whole-school actual',()=>assert.equal(factCards(model)[2].value,'待核对'));
test('kitchen does not report completion',()=>assert(stepBadge('kitchen',model).includes('未接入')));
test('dispatch does not report delivery',()=>assert(stepBadge('dispatch',model).includes('未接入')));
test('unavailable is not an empty success',()=>assert.equal(stepBadge('recipe',{...model,capabilities:{recipe:false}}),'按权限开放'));
test('bad scene action has no registry entry',()=>assert.equal(stepFor('finance'),null));
test('professional routes are strictly allowlisted',()=>{assert.equal(professionalRoute('https://evil.example'),null);assert.equal(professionalRoute('order'),null);assert(professionalRoute('order','/?x=//evil.example').startsWith('/desk/purchase-order/%2F'));});
test('unknown meal is only an expected draft',()=>{const row=mealDraft({student:'S',lunch:'未确认',lunch_expected:1});assert.equal(row.lunch,'就餐');assert(!('status' in row));});
test('confirmed non-eating overrides prior expectation',()=>assert.equal(mealDraft({student:'S',lunch:'未就餐',lunch_expected:1}).lunch,'不就餐'));
test('draft counts remain local',()=>assert.equal(draftTotals([mealDraft({student:'S',lunch_expected:1})]).lunch,1));
test('HTML escapes all source data',()=>assert.equal(esc('<script>"&'), '&lt;script&gt;&quot;&amp;'));
console.log(JSON.stringify({passed:true,cases:cases.length,checks:cases}));
