[Service]
ExecStart=
ExecStart=/usr/sbin/nginx -c /home/zyd/frappe/config/harness/nginx.conf -p /home/zyd/frappe/config/harness/ -g "daemon off;"
ExecReload=
ExecReload=/usr/sbin/nginx -c /home/zyd/frappe/config/harness/nginx.conf -p /home/zyd/frappe/config/harness/ -s reload
