"""Task-bound view tool; blueprint proposals do not activate database schemas."""
import argparse
import json
import os
from pathlib import Path


def use_site_os_identity(site_path):
    """The view bridge writes as the site service owner, even from root Codex.

    Frappe's set_user controls business permissions, not Unix file ownership.
    Drop root before initializing Frappe so proposals, logs and caches remain
    readable by the normal web worker. This does not affect the Codex parent.
    """
    if not hasattr(os, 'geteuid'):
        raise RuntimeError('The view bridge requires the native Linux site runtime')
    owner = site_path.stat()
    if owner.st_uid == 0:
        raise RuntimeError('The site must have a non-root service owner')
    if os.geteuid() == 0:
        import pwd
        account = pwd.getpwuid(owner.st_uid)
        os.initgroups(account.pw_name, owner.st_gid)
        os.setgid(owner.st_gid)
        os.setuid(owner.st_uid)
    elif os.geteuid() != owner.st_uid:
        raise RuntimeError('Run the view bridge as the site service owner')
    os.umask(0o077)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--site', required=True)
    parser.add_argument('--task', required=True)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--propose-business', help='Absolute path to a data-only business proposal JSON')
    mode.add_argument('--view', choices=['students', 'class_students', 'meal_counts', 'recipe_week', 'recipe_nutrition',
                        'business_catalog', 'business_list', 'business_record', 'stock', 'ingredient_nutrition', 'classroom_day', 'weekly_orders',
                        'project_catalog', 'frappe_catalog', 'frappe_doctype', 'frappe_new', 'frappe_document', 'frappe_report', 'frappe_page', 'frappe_workspace', 'business_blueprint'])
    parser.add_argument('--proposal-id', dest='proposal_id')
    parser.add_argument('--presentation', choices=['table', 'bars'])
    parser.add_argument('--components', nargs='+', choices=['stats', 'table', 'bars', 'notice', 'recipe_week'])
    parser.add_argument('--group')
    parser.add_argument('--day')
    parser.add_argument('--meal')
    parser.add_argument('--recipe')
    parser.add_argument('--garden-ratio', dest='garden_ratio', type=float)
    parser.add_argument('--standard-mode', dest='standard_mode', choices=['自动（按学生档案）', '手动估算'])
    parser.add_argument('--age-group', dest='age_group', choices=['4–6岁平均', '4岁', '5岁', '6岁'])
    parser.add_argument('--gender', choices=['男女平均', '男', '女'])
    parser.add_argument('--student-groups', dest='student_groups', nargs='+')
    for name in ('entity', 'record', 'keyword', 'period', 'start-date', 'end-date', 'status', 'company', 'warehouse', 'domain',
                 'app', 'module', 'doctype', 'document', 'report', 'page', 'workspace', 'kind'):
        parser.add_argument('--' + name)
    parser.add_argument('--offset', type=int)
    args = parser.parse_args()
    sites = Path('/home/zyd/frappe/native-bench/sites').resolve()
    if Path(args.site).name != args.site or not (sites / args.site / 'site_config.json').is_file():
        parser.error('Invalid site')
    proposal = None
    if args.propose_business:
        # A proposal generated by the root runner may itself be mode 0600.
        # Read only its bounded data before dropping identity, never execute it.
        path = Path(args.propose_business)
        if not path.is_absolute() or not path.is_file() or path.stat().st_size > 32768:
            parser.error('方案必须是本机绝对路径的有限大小 JSON 文件')
        with path.open('rb') as stream:
            raw = stream.read(32769)
        if len(raw) > 32768:
            parser.error('业务方案过大')
        proposal = raw.decode('utf-8')
    use_site_os_identity(sites / args.site)
    # Frappe's site log paths are relative to the sites directory even when
    # sites_path is absolute. The Codex command normally starts in the app repo.
    os.chdir(sites)
    import frappe
    frappe.init(site=args.site, sites_path=str(sites))
    frappe.connect()
    try:
        from tongjianyun.meal_views import publish_for_task
        if args.propose_business:
            from tongjianyun.business_blueprints import propose_for_task
            result = propose_for_task(args.task, proposal)
        else:
            requested = {k: v for k, v in vars(args).items() if k not in {'site', 'task', 'propose_business'} and v is not None}
            result = publish_for_task(args.task, requested)
        print(json.dumps(result, ensure_ascii=False, default=str))
    except Exception as error:
        print(json.dumps({'display_requested': False, 'error': str(error)[:400]}, ensure_ascii=False))
        raise SystemExit(1)
    finally:
        frappe.db.rollback()
        frappe.destroy()


if __name__ == '__main__':
    main()
